package cn.loveiszero.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KejuAssistant generated by hbm2java
 */
@Entity
@Table(name = "keju_assistant", catalog = "nsh_keju")
public class KejuAssistant implements java.io.Serializable {

	private Integer id;
	private String questionDetail;
	private String answerDetail;
	private Date createTime;
	private Date updateTime;

	public KejuAssistant() {
	}

	public KejuAssistant(Integer questionId, String questionDetail, Integer answerId, String answerDetail,
			Date createTime, Date updateTime) {
		
		this.questionDetail = questionDetail;
		
		this.answerDetail = answerDetail;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	@Column(name = "question_detail")
	public String getQuestionDetail() {
		return this.questionDetail;
	}

	public void setQuestionDetail(String questionDetail) {
		this.questionDetail = questionDetail;
	}


	@Column(name = "answer_detail")
	public String getAnswerDetail() {
		return this.answerDetail;
	}

	public void setAnswerDetail(String answerDetail) {
		this.answerDetail = answerDetail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
