server:
  port: 8082
  session-timeout: 30
  tomcat.uri-encoding: UTF-8

spring:  
  datasource:  
    driver-class-name: com.mysql.jdbc.Driver  
    url: jdbc:mysql://localhost:3306/nsh_keju?useUnicode=true&characterEncoding=UTF-8 
    username: root  
    password:   
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
      



